# Generated by Django 4.0.5 on 2022-09-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='number',
            new_name='mobile',
        ),
    ]
