# Generated by Django 4.0.5 on 2022-09-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_number_data_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(max_length=20)),
                ('customer_id', models.IntegerField(max_length=20)),
                ('logs', models.CharField(max_length=5000)),
            ],
        ),
    ]
