# Generated by Django 4.0.5 on 2022-09-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_order_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utility_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('_type', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
