# Generated by Django 4.0.5 on 2022-09-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_delete_data_delete_order_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utility_data',
            name='password',
        ),
    ]
