# Generated by Django 4.0.5 on 2022-09-18 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_email_order_data__email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_data',
        ),
    ]
