# Generated by Django 4.0.5 on 2022-09-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_delete_order_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=50)),
                ('_email', models.EmailField(max_length=50)),
                ('_from', models.CharField(max_length=50)),
                ('_to', models.CharField(max_length=50)),
                ('_size', models.CharField(max_length=50)),
                ('_weight', models.CharField(max_length=50)),
                ('_time', models.CharField(max_length=50)),
                ('_orderid', models.CharField(max_length=50)),
                ('_status', models.CharField(max_length=50)),
                ('_status_log', models.CharField(max_length=500)),
                ('_current_location', models.CharField(max_length=50)),
            ],
        ),
    ]
