# Generated by Django 4.0.5 on 2022-09-18 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_transport_data_warehouse_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse_data',
            name='_email',
        ),
        migrations.RemoveField(
            model_name='warehouse_data',
            name='_from',
        ),
        migrations.RemoveField(
            model_name='warehouse_data',
            name='_size',
        ),
        migrations.RemoveField(
            model_name='warehouse_data',
            name='_to',
        ),
    ]
